<section>
        <table>
            <tbody>
                <!-- temp row-->
                <tr>
                    <td>Biljettnummer:
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>Film:
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>Datum:
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>Tid:
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>Salong:
                    </td>
                    <td>
                    </td>
                </tr>
                <tr>
                    <td>Antal:
                    </td>
                    <td>
                    </td>
                </tr>
            </tbody>
        </table>
    </section>